spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/book_shop
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  sql:
    init:
      mode: never

#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false