spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_shop
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
